### ISSUE TITLE
Looks amazing!

### ISSUE THREAD

**Issue by flacial** [Yilliee/Yilliee#1]
🔥 🔥 🔥 🔥

**Comment by FiestaLake** [comment]
> 🔥 🔥 🔥 🔥

DUDE WHAT"S THE POINT OF WRITING COMMENTS VIA ISSUES?

**Comment by saltyming** [comment]
Btw, @Yilliee How about this?

    I'm an average 17 years old person. 

    I tried to install TWRP for the first time in March 2020. The only reason to do it is to root my Galaxy J5 prime to try 
    installing Fortnite on the ARM32 device.
    I was able to root but failed miserably in my goal XD (try to figure out why) .
    
    On the other hand, thanks to @asarr22 's Project Radical and Project Kebab, I learned tons of things about Android 
    tweaking and the lack of development for that device, which led to me try to develop it myself.

**Comment by Yilliee** [comment]
> Btw, @Yilliee How about this?
> 
> ```
> I'm an average 17 years old person. 
> 
> I tried to install TWRP for the first time in March 2020, The only reason to do it is to root my Galaxy J5 prime to try 
> installing Fortnite on the ARM32 device.
> I was able to root but failed miserably in my goal XD (try to figure out why) 
> 
> On the other hand, thanks to @asarr22 's Project Radical and Project Kebab, I learned tons of things about Android 
> tweaking and the lack of development for that device, which led to me try to develop it myself. 
> ```

Seems okay but ain't in the mood to edit bio rn.
Might do it later.

Thnx for the suggestion

**Comment by Yilliee** [comment]
> 🔥 🔥 🔥 🔥

Very nice thing to open an issue for lol
